Simple RBAC solution for the admin API
neicnordic/sensitive-data-archive pull request #1115
Opened 2024-11-04 14:04 UTC by jbygdell

**Description**
Minimalistic RBAC solution for the admin API.

Currently only 2 roles are in use `admin` and `helpdesk`

2024-11-05 09:46 UTC, viklund requested changes
Role names should not be hardcoded.

It should be possible to define new roles without changing the go source code, and what endpoints they have access to.

2024-11-05 13:36 UTC, jbygdell commented
> Role names should not be hardcoded.
> 
> It should be possible to define new roles without changing the go source code, and what endpoints they have access to.

That would make this extremely complex to almost no gain.
You better come up with some reasonable scenarios where this will be beneficial before we spend the time to implement it.

2024-11-06 10:07 UTC, viklund commented
> > Role names should not be hardcoded.
> > It should be possible to define new roles without changing the go source code, and what endpoints they have access to.
> 
> That would make this extremely complex to almost no gain. You better come up with some reasonable scenarios where this will be beneficial before we spend the time to implement it.

The code in this file should not become more complicated (probably less). It's basically one annotation per endpoint. RBAC is a solved problem.

2024-11-21 10:38 UTC, MalinAhlberg reviewed
Looks good! I added some minor suggestions for the documentaiton. Will do some testing before I approve.

2024-11-21 10:38 UTC, MalinAhlberg commented on sda/cmd/api/api.md
> +RBAC is configure according to the JSON schema below.
```suggestion
RBAC is configured according to the JSON schema below.
```

2024-11-21 10:38 UTC, MalinAhlberg commented on sda/cmd/api/api.md
> +The `policy` section will configure access to the defined endpoints, unless specific rules are set, an endpoint will not be accessible
```suggestion
The `policy` section will configure access to the defined endpoints. Unless specific rules are set, an endpoint will not be accessible
```

2024-11-21 10:38 UTC, MalinAhlberg commented on sda/cmd/api/api.md
> +- `paht`: have two different wildcard notations `*`, matches any value and `:` that matches a specifc named value
```suggestion
- `path`: the endpoint. Should be a string value with two different wildcard notations: `*` matches any value and `:` that matches a specific named value
```

2024-11-21 10:38 UTC, MalinAhlberg commented on sda/cmd/api/api.md
> +- `role`: is the role that will be able to access the path, `"*"` will match any role or user.
```suggestion
- `role`: the role that will be able to access the path, `"*"` will match any role or user.
```

2024-11-21 12:54 UTC, MalinAhlberg approved these changes
Good work!

2024-11-21 15:40 UTC, nanjiangshu commented on sda/cmd/api/api.md
> +The `policy` section will configure access to the defined endpoints. Unless specific rules are set, an endpoint will not be accessible
```suggestion
The `policy` section will configure access to the defined endpoints. Unless specific rules are set, an endpoint will not be accessible.
```

2024-11-22 09:43 UTC, nanjiangshu approved these changes
Looks good!

2024-11-22 10:28 UTC, MalinAhlberg approved these changes

2024-11-22 10:50 UTC, merged