Documentation for local kubernetes using k3d
neicnordic/sensitive-data-archive pull request #1181
Opened 2024-12-10 09:10 UTC by jbygdell

**Related issue(s) and PR(s)**  
This PR closes #1154 .

**Description**
This PR adds information on how to work with the helm charts locally in order to quickly test changes in the helm charts, there are a few things that can not be fully tested yet, such as ingress.

**How to test**
* Follow the documentation on how to create a cluster and deploy a chart.
* Use your knowledge of how [helm](https://helm.sh/) and [kubernetes](https://kubernetes.io/) work to verify that the app is deployed with the expected configurations. Or why it failed if it did.

2024-12-11 09:44 UTC, nanjiangshu commented on README.md
> +Developing and testing the helm charts (or other deployment manifests) requires an kubernetes environment. One of the most light weight distributions avilable is [k3d](https://k3d.io/stable/).
```suggestion
Developing and testing the Helm charts (or other deployment manifests) requires a Kubernetes environment. One of the most lightweight distributions available is [k3d](https://k3d.io/stable/).
```

2024-12-11 09:50 UTC, jbygdell commented on .github/integration/scripts/charts/dependencies.sh
> +if [ -z "$1" ]; then
It skips it because commands that use `sudo` should never run in a scripted fashion.

But I'll add a sanity checking part to the script.

2024-12-11 09:50 UTC, nanjiangshu commented on README.md
> +bash .github/integration/scripts/charts/deploy_charts.sh sda-db "$(date +%F)" false s3
```suggestion
bash .github/integration/scripts/charts/deploy_charts.sh sda-svc "$(date +%F)" false s3
```

2024-12-11 09:54 UTC, nanjiangshu commented on README.md
> +- make k3d-cleanup-all-deployments - Remove all deployed components and dependencies
```suggestion
- `make k3d-deploy-dependencies` - bootstrap dependencies
- `make k3d-import-images` - build and import images into the default cluster named `k3s-default`
- `make k3d-deploy-postgres` - deploy the sda-db chart without TLS
- `make k3d-deploy-rabbitmq` - deploy the sda-mq chart without TLS
- `make k3d-deploy-sda-s3` - deploy the sda-svc chart with S3 storage without TLS
- `make k3d-deploy-sda-posix` - deploy the sda-svc chart with POSIX storage without TLS
- `make k3d-cleanup-all-deployments` - Remove all deployed components and dependencies
```

2024-12-11 09:56 UTC, nanjiangshu commented on README.md
> +Or by using the `make k3d-create-cluster` command, creates a cluster named `k3s-default`.
```suggestion
Or by using the `make k3d-create-cluster` command, you can create a cluster named `k3s-default`.
```

2024-12-11 09:57 UTC, nanjiangshu commented on README.md
> +The new cluster's connection details will automatically be merged into your default kubeconfig and activated, the command below should show the created node.
```suggestion
The new cluster's connection details will automatically be merged into your default kubeconfig and activated. The command below should show the created node.
```

2024-12-11 10:04 UTC, nanjiangshu reviewed
I followed the instructions and it worked like a charm. Great job!
Apart from some minor comments, I think it will be great to add a small section about how to verify that deployed SDA is working. This can be very basic and then link to other source (if there is any) for more detailed testing.

2024-12-11 15:01 UTC, nanjiangshu commented
Although all charts are deployed successfully, I was not able to obtain a token from the oidc-server (from a container within the cluster) 
```
curl http://oidc-server:8080/tokens 
{"error":"invalid_request","error_description":"unrecognized route"}
```

2024-12-11 15:05 UTC, nanjiangshu commented
I also found a typo in the script `oidc.py` https://github.com/neicnordic/sensitive-data-archive/blob/main/.github/integration/sda/oidc.py#L171. Token endpoint should be `/tokens` instead of `/token`. The easiest will be to solve it in the currently opened issues.

2024-12-12 07:27 UTC, jbygdell commented
> I also found a typo in the script `oidc.py` https://github.com/neicnordic/sensitive-data-archive/blob/main/.github/integration/sda/oidc.py#L171. Token endpoint should be `/tokens` instead of `/token`. The easiest will be to solve it in the currently opened issues.

It's not a typo, if you look closely you will see that the OIDC deployment actually uses a prebuild container.
But in order to make things similar during testing we should use the `oidc.py` file as that is used in the docker compose setup.

2024-12-12 11:03 UTC, nanjiangshu commented
Any ideas why I get this when running ` make k3d-deploy-sda-s3`? I haven't encountered this yesterday when I tried. 

```
+ helm install pipeline charts/sda-svc --set image.tag=PR2024-12-12 --set image.pullPolicy=IfNotPresent --set global.tls.enabled=false --set global.broker.port=5672 --set global.archive.storageType=s3 --set global.backupArchive.storageType=s3 --set global.inbox.storageType=s3 --set global.sync.api.password=pass --set global.sync.api.user=user --set global.sync.remote.host=https://sync-api -f /tmp/values.yaml --wait
W1212 11:58:21.235130 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
W1212 11:58:21.235778 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
W1212 11:58:21.251943 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
W1212 11:58:21.279160 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
W1212 11:58:21.457555 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
```

and 

```
$ kubectl get pods | grep Crash
pipeline-sda-svc-auth-868b7c77b9-sqvql        0/1     CrashLoopBackOff   5 (80s ago)   4m22s
pipeline-sda-svc-ingest-69f54bfcb9-dr556      0/1     CrashLoopBackOff   5 (78s ago)   4m22s
pipeline-sda-svc-reencrypt-66dc49b499-2s4lr   0/1     CrashLoopBackOff   5 (81s ago)   4m22s
pipeline-sda-svc-sync-54d7cdd66b-2wfkq        0/1     CrashLoopBackOff   5 (78s ago)   4m22s
pipeline-sda-svc-verify-775b4476c8-bg4ll      0/1     CrashLoopBackOff   5 (69s ago)   4m22s
```

2024-12-12 11:58 UTC, jbygdell commented
> Any ideas why I get this when running ` make k3d-deploy-sda-s3`? I haven't encountered this yesterday when I tried.
> 
> ```
> + helm install pipeline charts/sda-svc --set image.tag=PR2024-12-12 --set image.pullPolicy=IfNotPresent --set global.tls.enabled=false --set global.broker.port=5672 --set global.archive.storageType=s3 --set global.backupArchive.storageType=s3 --set global.inbox.storageType=s3 --set global.sync.api.password=pass --set global.sync.api.user=user --set global.sync.remote.host=https://sync-api -f /tmp/values.yaml --wait
> W1212 11:58:21.235130 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> W1212 11:58:21.235778 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> W1212 11:58:21.251943 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> W1212 11:58:21.279160 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> W1212 11:58:21.457555 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> ```
> 
> and
> 
> ```
> $ kubectl get pods | grep Crash
> pipeline-sda-svc-auth-868b7c77b9-sqvql        0/1     CrashLoopBackOff   5 (80s ago)   4m22s
> pipeline-sda-svc-ingest-69f54bfcb9-dr556      0/1     CrashLoopBackOff   5 (78s ago)   4m22s
> pipeline-sda-svc-reencrypt-66dc49b499-2s4lr   0/1     CrashLoopBackOff   5 (81s ago)   4m22s
> pipeline-sda-svc-sync-54d7cdd66b-2wfkq        0/1     CrashLoopBackOff   5 (78s ago)   4m22s
> pipeline-sda-svc-verify-775b4476c8-bg4ll      0/1     CrashLoopBackOff   5 (69s ago)   4m22s
> ```

have you imported the images?
make build-all
make k3d-import-images

2024-12-12 12:35 UTC, nanjiangshu commented
> > Any ideas why I get this when running ` make k3d-deploy-sda-s3`? I haven't encountered this yesterday when I tried.
> > ```
> > + helm install pipeline charts/sda-svc --set image.tag=PR2024-12-12 --set image.pullPolicy=IfNotPresent --set global.tls.enabled=false --set global.broker.port=5672 --set global.archive.storageType=s3 --set global.backupArchive.storageType=s3 --set global.inbox.storageType=s3 --set global.sync.api.password=pass --set global.sync.api.user=user --set global.sync.remote.host=https://sync-api -f /tmp/values.yaml --wait
> > W1212 11:58:21.235130 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> > W1212 11:58:21.235778 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> > W1212 11:58:21.251943 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> > W1212 11:58:21.279160 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> > W1212 11:58:21.457555 3908905 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].labelSelector: a null labelSelector results in matching no pod
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > $ kubectl get pods | grep Crash
> > pipeline-sda-svc-auth-868b7c77b9-sqvql        0/1     CrashLoopBackOff   5 (80s ago)   4m22s
> > pipeline-sda-svc-ingest-69f54bfcb9-dr556      0/1     CrashLoopBackOff   5 (78s ago)   4m22s
> > pipeline-sda-svc-reencrypt-66dc49b499-2s4lr   0/1     CrashLoopBackOff   5 (81s ago)   4m22s
> > pipeline-sda-svc-sync-54d7cdd66b-2wfkq        0/1     CrashLoopBackOff   5 (78s ago)   4m22s
> > pipeline-sda-svc-verify-775b4476c8-bg4ll      0/1     CrashLoopBackOff   5 (69s ago)   4m22s
> > ```
> 
> have you imported the images? make build-all make k3d-import-images

Yes, I have done that. Actually have started from scratch once again as well.

2024-12-12 13:29 UTC, aaperis commented
The `dependecies.sh` script fails to run for me. First `sign_jwt.sh` complains about 
```
apt-get -o DPkg::Lock::Timeout=60 update >/dev/null
apt-get -o DPkg::Lock::Timeout=60 install -y jq xxd >/dev/null
```
and then `yq`:
```
yq: -i/--in-place can only be used with -y/-Y
```

2024-12-12 13:47 UTC, aaperis requested changes
Seems like a great setup adding stuff in the make file, however I tried to test in ubuntu, but got some errors.

2024-12-12 13:53 UTC, jbygdell commented
> The `dependecies.sh` script fails to run for me. First `sign_jwt.sh` complains about
> 
> ```
> apt-get -o DPkg::Lock::Timeout=60 update >/dev/null
> apt-get -o DPkg::Lock::Timeout=60 install -y jq xxd >/dev/null
> ```
> 
> and then `yq`:
> 
> ```
> yq: -i/--in-place can only be used with -y/-Y
> ```

That script needs a check to see if the UID is 0, if it is any other UID the install should not be triggered.
Our scripts should not install stuff, you need to do that your self.

2024-12-12 13:57 UTC, nanjiangshu approved these changes
LGTM!

2024-12-12 14:11 UTC, jbygdell commented
> Seems like a great setup adding stuff in the make file, however I tried to test in ubuntu, but got some errors.

@aaperis what version of yq have you installed?
The script works with `v4.20.1` or above from the github repo.

2024-12-12 14:38 UTC, aaperis commented
> > Seems like a great setup adding stuff in the make file, however I tried to test in ubuntu, but got some errors.
> 
> @aaperis what version of yq have you installed? The script works with `v4.20.1` or above from the github repo.

Installed via apt: 
```
$ yq --version
yq 0.0.0
```
:laughing:

I will fetch the latest from the github repo and retry.

2024-12-12 14:55 UTC, aaperis approved these changes
Works like a charm :smile:

2024-12-12 15:45 UTC, nanjiangshu approved these changes

2024-12-13 07:21 UTC, merged