Bigpicture data replication conponents
neicnordic/sensitive-data-archive pull request #365
Opened 2023-10-20 12:48 UTC by jbygdell

2023-11-15 12:10 UTC, dbampalikis requested changes

2023-11-15 12:10 UTC, dbampalikis commented on sda/cmd/syncapi/syncapi.go
> +		}
```suggestion
		corrID := uuid.New().String()
		if err := Conf.API.MQ.SendMessage(corrID, Conf.Broker.Exchange, Conf.SyncAPI.IngestRouting, ingestMsg); err != nil {
			return fmt.Errorf("failed to send ingest messge: Reason %v", err)
		}

		accessionIDs = append(accessionIDs, files.FileID)
		finalize := schema.IngestionAccession{
			Type:               "accession",
			User:               blob.User,
			FilePath:           files.FilePath,
			AccessionID:        files.FileID,
			DecryptedChecksums: []schema.Checksums{{Type: "sha256", Value: files.ShaSum}},
		}
		finalizeMsg, err := json.Marshal(finalize)
		if err != nil {
			return fmt.Errorf("failed to marshal json messge: Reason %v", err)
		}

		if err := Conf.API.MQ.SendMessage(corrID, Conf.Broker.Exchange, Conf.SyncAPI.AccessionRouting, finalizeMsg); err != nil {
			return fmt.Errorf("failed to send mapping messge: Reason %v", err)
		}
```

2023-11-15 12:10 UTC, dbampalikis commented on sda/cmd/syncapi/syncapi.go
> +	"github.com/gorilla/mux"
```suggestion
	"github.com/google/uuid"
	"github.com/gorilla/mux"
```

2023-11-15 12:19 UTC, jbygdell commented on sda/cmd/syncapi/syncapi.go
> +	r := mux.NewRouter().SkipClean(true)
Then we need to do a full refactoring, better to save that for later.

2023-11-16 07:55 UTC, dbampalikis approved these changes
Looks good and with the latest fixes it works out of the box!

2023-11-17 09:35 UTC, aaperis approved these changes

2023-11-17 09:54 UTC, merged