[sda-auth] Make elixir endpoint optional
neicnordic/sensitive-data-archive pull request #401
Opened 2023-11-06 14:56 UTC by dbampalikis

This PR makes the Elixir endpoint of the sda-auth optional. Specifically, if the variables `Elixir_id` or `Elixir_secret` are not set, the sda-auth is running only with the EGA option.

Also, in case neither the EGA nor the Elixir options are set, the service will return an error, letting the user know that it cannot start.

The PR is now deployed on the fega-test namespace

2023-11-06 22:08 UTC, kusalananda requested changes
Logic hiccup.

2023-11-06 22:26 UTC, dbampalikis commented on sda-auth/config.go
> +	if (elixir.ID == "" && elixir.Secret == "") && (cega.ID == "" && cega.Secret == "") {
:sweat_smile: you are right, not sure what I was thinking :smile:

2023-11-07 10:07 UTC, kusalananda submitted a review, later dismissed

2023-11-07 10:31 UTC, pontus commented on sda-auth/main.go
> +		// Elixir is always available
```suggestion
		// Elixir is configured, offer it
```

2023-11-07 10:32 UTC, pontus submitted a review, later dismissed

2023-11-07 10:34 UTC, pontus commented
Possibly add a test case verifying that lack of configuration results in failure?

2023-11-07 11:13 UTC, kusalananda submitted a review, later dismissed

2023-11-07 12:22 UTC, dbampalikis commented
> Possibly add a test case verifying that lack of configuration results in failure?

Makes sense, added a couple of cases for this configuration

2023-11-07 13:34 UTC, pontus approved these changes

2023-11-07 13:41 UTC, kostas-kou submitted a review, later dismissed

2023-11-07 15:35 UTC, kusalananda submitted a review, later dismissed
3rd time's the charm

2023-11-08 09:15 UTC, kusalananda approved these changes

2023-11-08 12:38 UTC, aaperis approved these changes
Looks good, minor typo :-)

2023-11-08 12:38 UTC, aaperis commented on sda-auth/README.md
> +The `sda-auth` allows for two different type of login providers: `EGA` and `Elixir` (LS-AAI). It is possible, however, to run the `sda-auth` using only one of the parameters. In order to remove the `
```suggestion
The `sda-auth` allows for two different type of login providers: `EGA` and `Elixir` (LS-AAI). It is possible, however, to run the `sda-auth` using only one of the providers. In order to remove the `EGA` option, remove the `CEGA_ID` and `CEGA_SECRET` options for the configuration, while for removing the `Elixir` option, remove the `ELIXIR_ID` and `ELIXIR_SECRET` variables.
```

2023-11-09 12:48 UTC, aaperis approved these changes

2023-11-09 12:54 UTC, kusalananda approved these changes

2023-11-09 12:58 UTC, merged