Merge sda-doa
neicnordic/sensitive-data-archive pull request #876
Opened 2024-05-27 10:42 UTC by Parisa68

**Related issue(s) and PR(s)**  
This PR closes issue #857 .

**Description**
Merges sda-doa into this repo.

2024-05-29 14:43 UTC, Parisa68 commented
https://github.com/dependabot rebase

2024-05-30 07:10 UTC, jbygdell requested changes
- The entire `.github` folder must be removed so we don't get any conflicts with regards to depenabot and such.
- The relevant parts of the workflows should be merged into the corresponding file of the root of the repo.

- The docker compose files should be moved into `.github/integration` in the root of the repo and be reworked similar to the existing compose files.
 
- Keys, certificates and such should be generated dynamically if needed and not be committed to the repository.
 
- Relevant options for this app should be added to the `Makefile`

2024-05-30 07:10 UTC, jbygdell commented on sda-doa/docker-compose-posix-outbox.yml
> +    image: uiobmi/localega-broker-private:latest
```suggestion
    build:
      context: ../../rabbitmq
    container_name: rabbitmq
    image: ghcr.io/neicnordic/sensitive-data-archive:PR${PR_NUMBER}-rabbitmq
```

2024-05-30 11:22 UTC, kjellp commented
Thanks @jbygdell ! We will start resolving as much as possible based on these comments. The plan is to have to PRs, an initial "import" one,  and a second "complete the integration tests " (with main repo root folder ).

2024-06-17 07:10 UTC, jbygdell approved these changes

2024-06-17 08:49 UTC, kjellp approved these changes
LGTM - remaining integrations are carried fwd in #901

2024-06-17 08:53 UTC, jbygdell reviewed
@Parisa68 do a `update with rebase` on this repo so it gets matched with main, then it can be merged more easily.

2024-06-17 12:17 UTC, merged